sonar.projectKey=core-cloud-gitghub-enterprise-terraform
sonar.projectName=Terraform Module for GitHub Enterprise
sonar.sources=.
sonar.exclusions=**/.terraform/**,**/test-results.xml,**/.scannerwork/**,**/*.tftest.hcl
sonar.tests=tests
sonar.test.inclusions=**/*.tftest.hcl
sonar.junit.reportPaths=test-results.xml
sonar.sourceEncoding=UTF-8